// Footer paw print, 28 columns by 24 rows: "t" toe, "p" pad, "L" letter, "." empty.
export const PAW_MASK: readonly string[] = [
  ".........tt......tt.........",
  "........tttt....tttt........",
  "........ttttt..ttttt........",
  "........ttttt..ttttt........",
  "........ttttt..ttttt........",
  "........ttttt..ttttt........",
  "..tttt...ttt....ttt...tttt..",
  "..ttttt..............ttttt..",
  "..ttttt..............ttttt..",
  "..ttttt..............ttttt..",
  "...tttt..............tttt...",
  "....tt....pppppppp....tt....",
  "........pppppppppppp........",
  ".......pppppppppppppp.......",
  "......ppLLLLpppLLppLLp......",
  "......pLLLLLLppLLppLLp......",
  ".....ppLLppppppLLppLLpp.....",
  ".....ppLLppppppLLLLLLpp.....",
  ".....ppLLppppppLLLLLLpp.....",
  ".....ppLLppppppLLppLLpp.....",
  ".....ppLLLLLLppLLppLLpp.....",
  ".....pppLLLLpppLLppLLpp.....",
  "......pppppppppppppppp......",
  "........ppp.pppp.ppp........",
];
